image: Visual Studio 2017

configuration:
  - Debug
  - Relase 
  
clone_folder: c:\projects\sc

platform:
- x86
- x64

install:
  - cd c:\projects\sc
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017" ..

build_script:
  - cmake -DBUILD_SHARED_LIBS=ON .
  - cmake --build .
  - cmake -DBUILD_SHARED_LIBS=OFF .
  - cmake --build .

deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 3yrHX802xf8XklCVuyiZ5pZYy8asont7WJdXXRBIgjG3JEyRp3KWmDaLdtrzKPbz
  artifact: /.*\.dll/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only