image: Visual Studio 2017

configuration:
  - Relase 
  
clone_folder: c:\projects\sc

platform:
- x86
- x64

artifacts:
  - path: '$(configuration)\**\*.dll'
    name: clipboard_lite_artifact
    
install:
  - cd c:\projects\sc
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017" ..

build_script:
  - cmake -DCMAKE_BUILD_TYPE=$(configuration) -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=c:\projects\sc\build\output .
  - cmake --build .
  - cmake -DCMAKE_BUILD_TYPE=$(configuration) -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=c:\projects\sc\build\output .
  - cmake --build .

deploy:
  provider: GitHub
  auth_token:
    secure: WCGi6SXwa6VaPyLH6fZCrmTix+e2FA3zwzhNg8dSf3EdrcecGIR3Z0qG/vssOdfA
  artifact: clipboard_lite_artifact
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true 
    