image: Visual Studio 2017

configuration:
  - Relase 
  
clone_folder: c:\projects\sc

platform:
- x86
- x64

artifacts:
  - path: '$(configuration)\**\*.dll'
    name: clipboard_lite_artifact
    
install:
  - ps: If ($env:Platform -Match "x86"){ $env:CMAKE_ARCH="" } Else { $env:CMAKE_ARCH=" Win64"}
  - mkdir C:\projects\deps
  - cd C:\projects\deps
  - set CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.0-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version
  - cd c:\projects\sc
  - mkdir build
  - cd build
  - cmake ..

build_script: 
  - cmake -DBUILD_SHARED_LIBS=ON .
  - cmake --build .
  - cmake -DBUILD_SHARED_LIBS=OFF .
  - cmake --build . 

deploy:
  provider: GitHub
  auth_token:
    secure: WCGi6SXwa6VaPyLH6fZCrmTix+e2FA3zwzhNg8dSf3EdrcecGIR3Z0qG/vssOdfA
  artifact: clipboard_lite_artifact
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true 
    