image: Visual Studio 2017

configuration:
  - Release 
  
clone_folder: c:\projects\sc

platform:
- x86
- x64
    
install:
  - ps: If ($env:Platform -Match "x86"){ $env:CMAKE_ARCH="" } Else { $env:CMAKE_ARCH=" Win64"}
  - cd c:\projects\sc
  - mkdir build
  - cd build
  - cmake ..
  
build_script: 
  - cmake -DBUILD_SHARED_LIBS=OFF .
  - cmake --build . --config %CONFIGURATION%
  - 7z a %CONFIGURATION%_%PLATFORM%_MT.zip -i!%APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%\*.dll -i!%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\*.lib
  - appveyor PushArtifact %CONFIGURATION%_%PLATFORM%_MT.zip
  - cmake -DBUILD_SHARED_LIBS=ON . 
  - cmake --build . --config %CONFIGURATION%
  - 7z a %CONFIGURATION%_%PLATFORM%_MT.zip -i!%APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%\*.lib
  - appveyor PushArtifact %CONFIGURATION%_%PLATFORM%_MT.zip
    
deploy:
  provider: GitHub
  auth_token:
    secure: WCGi6SXwa6VaPyLH6fZCrmTix+e2FA3zwzhNg8dSf3EdrcecGIR3Z0qG/vssOdfA 
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true 
    