image: Visual Studio 2017

configuration:
  - Relase 
  
clone_folder: c:\projects\sc

platform:
- x86
- x64

artifacts:
  - path: 'output\**\*.dll'
    name: clipboard_lite_artifact
    
install:
  - cd c:\projects\sc
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017" ..

build_script:
  - cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=c:\projects\sc\build\output .
  - cmake --build . --target install
  - cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=c:\projects\sc\build\output .
  - cmake --build . --target install

deploy:
  release: clipboard_lite-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 3yrHX802xf8XklCVuyiZ5pZYy8asont7WJdXXRBIgjG3JEyRp3KWmDaLdtrzKPbz
  artifact: clipboard_lite_artifact
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true 