image: Visual Studio 2017

configuration:
  - Relase 
  
clone_folder: c:\projects\sc

platform:
- x86
- x64

artifacts:
  - path: '$(configuration)\**\*.dll'
    name: clipboard_lite_artifact
    
install:
  - ps: If ($env:Platform -Match "x86"){ $env:CMAKE_ARCH="" } Else { $env:CMAKE_ARCH=" Win64"}
  - cd c:\projects\sc
  - mkdir build
  - cd build
  - cmake ..

build_script: 
  - cmake -DBUILD_SHARED_LIBS=ON .
  - cmake --build . --config Release
  - cmake -DBUILD_SHARED_LIBS=OFF .
  - cmake --build . --config $(configuration)
  
deploy:
  provider: GitHub
  auth_token:
    secure: WCGi6SXwa6VaPyLH6fZCrmTix+e2FA3zwzhNg8dSf3EdrcecGIR3Z0qG/vssOdfA
  artifact: clipboard_lite_artifact
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true 
    